#!/usr/bin/env bash
# Verifies the whole chain: Gateway -> IngressLink -> IPAM -> CIS -> BIG-IP.
NS=${NS:-gatewaylink-demo}
echo "== Gateway + data plane"
oc -n $NS get gateway gateway
oc -n $NS get svc gateway-nginx -o custom-columns='NAME:.metadata.name,TYPE:.spec.type,ETP:.spec.externalTrafficPolicy,PORTS:.spec.ports[*].nodePort'
oc -n $NS get pods -l gateway.networking.k8s.io/gateway-name=gateway -o wide

echo; echo "== ExternalLoadBalancer status"
oc -n $NS get externalloadbalancers.gateway.nginx.org gateway-bigip-link -o json \
  | jq -r '.status.controllers[]?.conditions[]? | "\(.type)=\(.status) \(.reason): \(.message)"'

echo; echo "== IngressLink generated by NGF (named after the data plane Service)"
oc -n $NS get ingresslinks.cis.f5.com -o custom-columns='NAME:.metadata.name,LABEL:.spec.ipamLabel,ADDRESS:.status.vsAddress,STATUS:.status.status'

echo; echo "== IPAM: requests (CIS) vs allocations (FIC)"
oc -n kube-system get ipams.fic.f5.com -o json | jq -r '.items[0] as $c
  | (["KEY","LABEL","IP"]|@tsv), (($c.spec.hostSpecs//[])[] as $r
  | [$r.key, $r.ipamLabel, ((($c.status.IPStatus//[])|map(select(.key==$r.key))|.[0].ip)//"pending")]|@tsv)' | column -t

echo; echo "== Writers on the IPAM resource (expect k8s-bigip-ctlr + f5-ipam-controller/status)"
oc -n kube-system get ipams.fic.f5.com -o json --show-managed-fields \
  | jq -c '.items[0].metadata.managedFields[] | {manager, subresource}'

echo; echo "== CIS log (last 3 min)"
oc -n kube-system logs deploy/f5-cis-f5-bigip-ctlr --since=3m | grep -iE "ingresslink|AS3|\[(ERROR|WARNING)\]" | tail -10
