apiVersion: v1
kind: Service
metadata:
  name: ngf-cp-metrics
  namespace: nginx-gateway
  labels: { app: ngf-cp-metrics }
spec:
  selector:
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: nginxgatewayfabric-mabuhay
  ports:
  - { name: metrics, port: 9113, targetPort: 9113 }
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ngf-cp
  namespace: nginx-gateway
spec:
  selector:
    matchLabels: { app: ngf-cp-metrics }
  endpoints:
  - port: metrics
    interval: 15s
