apiVersion: v1
kind: Service
metadata:
  name: ngf-dp-metrics
  namespace: default
  labels: { app: ngf-dp-metrics }
spec:
  selector:
    app.kubernetes.io/name: gateway-nginx
    gateway.networking.k8s.io/gateway-name: gateway
  ports:
  - { name: metrics, port: 9113, targetPort: 9113 }
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ngf-dp
  namespace: default
spec:
  selector:
    matchLabels: { app: ngf-dp-metrics }
  endpoints:
  - port: metrics
    interval: 15s
